### ISSUE TITLE
example mysql keygenerator

### ISSUE THREAD

**Issue by aspecialkey** [BraintagsGmbH/vertx-pojo-mapper#108]
hello,
i`m new to vertx and i`d like it to use with an orm.
now i`ve problems to get startet with the keygenerator. 
when i work with debuggenerator everything works fine but i don`t know how to work with defaultkeyhenerator.
So it was nice to have an example therefore.

best regards

**Comment by remi128** [comment]
did you check the documentation [here](https://github.com/BraintagsGmbH/vertx-pojo-mapper/blob/develop/vertx-pojo-mapper-common/src/docs/asciidoc/java/index.adoc#keygenerator)? You will need to have a running KeyGeneratorVerticle from the project [vertx-key-generator](https://github.com/BraintagsGmbH/vertx-key-generator/blob/master/src/docs/asciidoc/java/index.adoc) at your event bus

**Comment by aspecialkey** [comment]
thanks for reply! 

have you an example for the settingsfile for mysql? 

INFORMATION: settings successfully loaded from
src/main/conf/kgSettings.json
java.lang.InstantiationException:
de.braintags.io.vertx.pojomapper.mapping.impl.keygen.DefaultKeyGenerator

Am 2017-06-16 19:40, schrieb Michael Remme:

> did you check the documentation here [1]? You will need to have a running KeyGeneratorVerticle from the project vertx-key-generator [2] at your event bus 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1]
https://github.com/BraintagsGmbH/vertx-pojo-mapper/blob/develop/vertx-pojo-mapper-common/src/docs/asciidoc/java/index.adoc#keygenerator
[2]
https://github.com/BraintagsGmbH/vertx-key-generator/blob/master/src/docs/asciidoc/java/index.adoc
[3]
https://github.com/BraintagsGmbH/vertx-pojo-mapper/issues/108#issuecomment-309088823
[4]

**Comment by remi128** [comment]
please build a reproducer

**Comment by aspecialkey** [comment]
i think the problem is, that it doesnt exist a MySqlKeyGenerator like the MongoKeyGenerator.
i have to implement it myself or am im wrong?

[https://github.com/BraintagsGmbH/vertx-key-generator/tree/master/src/main/java/de/braintags/io/vertx/keygenerator/impl](https://github.com/BraintagsGmbH/vertx-key-generator/tree/master/src/main/java/de/braintags/io/vertx/keygenerator/impl)

**Comment by remi128** [comment]
No, it can't be that. The MongoKeyGenerator is a KeyGenerator, which uses a Mongo-DB as source to store the generated keys and deliver them to the requester

**Comment by remi128** [comment]
or to be more clear: if you want absolutely that the IDs are generated by a MySQL, then you should implement an suitable KeywordGenerator. If not, then launch a MongoDb parallel to your MySQL, which does not use a lot of resources, and use the MongoKeyGenerator
