### ISSUE TITLE
FileKeyGenerator improvement

### ISSUE THREAD

**Issue by remi128** [BraintagsGmbH/vertx-pojo-mapper#19]
FileKeyGenerator: save one file per entry, failover solution

**Comment by wwteo** [comment]
Could not find the FileKeyGenerator.java

**Comment by remi128** [comment]
sorry for the late reply, currently i am offline for some days.
FileKeyGenerator is no more existing in pojo mapper, since it was moved into a verticle named https://github.com/BraintagsGmbH/vertx-key-generator, which is still work in progress. Documentation will follow

**Comment by remi128** [comment]
documentation updated for vertx-pojo-mapper and vertx-keygenerator
