### ISSUE TITLE
No id-field specified in mapper

### ISSUE THREAD

**Issue by xarv** [BraintagsGmbH/vertx-pojo-mapper#41]
without the setting of id field the saving of model is failing with the below stacktrace.

`de.braintags.io.vertx.pojomapper.exception.MappingException: No id-field specified in mapper com.example.company.models.Tracker
        at de.braintags.io.vertx.pojomapper.mapping.impl.Mapper.validate(Mapper.java:181)
        at de.braintags.io.vertx.pojomapper.mapping.impl.Mapper.init(Mapper.java:142)
        at de.braintags.io.vertx.pojomapper.mapping.impl.Mapper.<init>(Mapper.java:120)
        at de.braintags.io.vertx.pojomapper.mongo.mapper.MongoMapper.<init>(MongoMapper.java:36)`

if i set the id field with a attribute then the save proceeds successfully.
version i am using 1.3.1

**Comment by remi128** [comment]
Currently the pojo mapper requires an ID field to be specified, so that single records can be loaded, updated etc. 
Do you have the requirement to use pojos without an identifyer?
To enable the possibility to use any existing POJO, there exists issue #11 to enable external mapping definitions.

**Comment by xarv** [comment]
well actually i am specifying one field in my pojo as an id field but i am not assigning any uuid to it. shouldn't it initialise the object id by itself when saving?

**Comment by remi128** [comment]
Yes, normally it should read the id generated by the database and in case of mongo it does. Unfortunately the mysql driver doesn't return the id, we are waiting for the implementation inside the mysqldriver.
If you are using mysql, then you can use the concept of KeyGenerator, to let generate a local id very fast:

Add another verticle like described here: https://github.com/BraintagsGmbH/vertx-key-generator/blob/master/src/docs/asciidoc/java/index.adoc

Add the annotation @KeyGenerator(value = DefaultKeyGenerator.NAME) to your pojo header

**Comment by xarv** [comment]
Thanks for clearing this out, as a matter of fact i am using mongo db which is why this is puzzling. I have followed the examples present here https://github.com/BraintagsGmbH/vertx-pojo-mapper/blob/master/vertx-pojo-mapper-common/src/docs/asciidoc/java/index.adoc#creating-a-mapper ,  initialising the object and leaving the id field empty and when trying to save it after which i am facing the above error.  If this is expected then i will work around it else we can dig a little deeper.

**Comment by remi128** [comment]
no, this is not expected. I will check the unit tests tomorrow, cause i saw, that the unit tests seem to use all the keygenerator as default.

**Comment by remi128** [comment]
ok, i checked, this is a bug. We will fix it in the coming 1.4.0

**Comment by remi128** [comment]
fixed and merged into branch develop; implications on mysql will be coming later
