### ISSUE TITLE
Extension of query for variable field values and caching

### ISSUE THREAD

**Issue by sschmittBt** [BraintagsGmbH/vertx-pojo-mapper#53]
For other requirements,  it's vital that queries can be cached as near to completion as possible, but that some variable conditions can still be resolved during execution of a cached query.
For this, two things are needed:

1. the query needs to be able to resolve variable field conditions. This should only be done during execution and should not influence the state of the query.

2. the build of a query expression should be sped up through caching of intermediate results that will not change during multiple executions

Since the limit (and offset) of a query often change without really changing the query itself, they should be extracted from the query and given directly during the execution as parameter. That way, even a query that is used for a pagination on a website can be cached.

**Comment by remi128** [comment]
merged into develop
