### ISSUE TITLE
Detect Setters with Lower Visibility than public

### ISSUE THREAD

**Issue by mpluecker** [BraintagsGmbH/vertx-pojo-mapper#58]
We want to implement POJOs with setters that are only used in the mapping process. Thus, the setters have a visibility of protected or default. We need an annotation to definie the minimum visibility for getters and setters for the process of detecting mapped fields.

**Comment by kerko** [comment]
When we do this, we should do it right. Since jackson for example also supports private setters, we should enable that to. That way its possible to defined setters only used for serialization and nothing else ever.

**Comment by remi128** [comment]
finished by #71
